add check file type is fifo
containerd/fifo pull request #53
Opened 2023-04-24 08:32 UTC by ningmingxiao

2023-04-26 23:33 UTC, estesp approved these changes

2023-04-27 09:43 UTC, fuweid commented on fifo.go
> +		if file.Mode()&os.ModeNamedPipe == 0 {
Would you please add a test for it? Thanks!

2023-04-27 16:13 UTC, fuweid requested changes

2023-04-28 01:38 UTC, fuweid approved these changes
LGTM

2023-04-28 16:50 UTC, merged